### ISSUE TITLE
.CSV file not generated

### ISSUE THREAD

**Issue by CyGregar** [SR-G/bambu-lab-observer#2]
Greetings, 

I have recently been doing some tests with Observer 1.0.2 and I noticed that the program is not generating the .csv file while it is running.

.json config file:

```
{
  "BambuLabPrinters" : [ 
      {
        "IP" : "192.168.xxx.xxx",
        "MQTTTLS" : true,
        "MQTTUsername" : "bblp",
        "MQTTPassword" : "xxxxxxxx"
      }
  ],
  "CSVFileName" : "bambu_lab_observer.csv",
  "LogLevel" : "INFO",
  "Topics" : [ "device/+/report" ],
  "PolicyAboutRegisterStartOfPrint" : "FIRST_MESSAGE_TIMESTAMP"
}
```
testing in windows_386 and windows_amd64
printer: X1C
Firmware: 01.06.05.01

**Comment by SR-G** [comment]
Hello.
The current behavior is for the CSV file to be generated only once : when a print is finished (either successfully, either with a print failure, ...).
So : 
- is the CSV generated on your side at the end (but not during the print, which is - at least for now - expected) ?
- or is the CSV _never_ generated, not even at the end of the print ?

Otherwise : 
- What are the logs saying (is there some errors anywhere) ?
- Do you have (i suppose the answer is yes, but just in case) write access to the folder in which the .CSV file is generated (= current folder in which the binary sits)

**Comment by CyGregar** [comment]
The .csv is generated correctly when printing is completed. 

My mistake in thinking that the .csv was updating as the printer server published the current printing status.

**Comment by SR-G** [comment]
No problem. Closing for now. Log + doc will be made clearer about this behavior (i'm not sure there would be some benefits about the .CSV being constantly updated during execution).
